### ISSUE TITLE
error when confirming community supported 

### ISSUE THREAD

**Issue by timberbee** [PaloAltoNetworks/prismacloud-cli#84]
## Describe the bug

When I run 
pc version
and try to answer yes to the #Community Supported verbage, I get a Traceback error. 
(pcclitest) ➜  pcclitest pc version
zsh: correct 'pc' to 'cp' [nyae]? n
# Community Supported
This template/solution is released under an as-is, best effort,
support policy. These scripts should be seen as community
supported and Palo Alto Networks will contribute our expertise as
and when possible. We do not provide technical support or help in
using or troubleshooting the components of the project through our
normal support options such as Palo Alto Networks support teams,
or ASC (Authorized Support Centers) partners and backline support
options. The underlying product used (Prisma Cloud) by the scripts
or templates are still supported, but the support is only for the
product functionality and not for help in deploying or using the
template or script itself.

Unless explicitly tagged, all projects or work posted in our
GitHub repository (at https://github.com/PaloAltoNetworks) or
sites other than our official Downloads page on
https://support.paloaltonetworks.com are provided under the best
effort policy.

Type yes to confirm you have read the message above: yes
Message accepted.
Traceback (most recent call last):
  File "/Users/[someuser]/Projects/pcclitest/bin/pc", line 8, in <module>
    sys.exit(cli())
  File "/Users/[someuser]/Projects/pcclitest/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/[someuser]/Projects/pcclitest/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/[someuser]/Projects/pcclitest/lib/python3.9/site-packages/click/core.py", line 1651, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/Users/[someuser]/Projects/pcclitest/lib/python3.9/site-packages/click_help_colors/core.py", line 101, in resolve_command
    cmd_name, cmd, args[1:] = super(HelpColorsMultiCommand, self).resolve_command(ctx, args)
  File "/Users/[someuser]/Projects/pcclitest/lib/python3.9/site-packages/click/core.py", line 1698, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/Users[someuser]/Projects/pcclitest/lib/python3.9/site-packages/prismacloud/cli/__init__.py", line 135, in get_command
    mod = __import__(f"prismacloud.cli.{module_type}.cmd_{cmd_name}", None, None, ["cli"])
  File "/Users/[someuser]/Projects/pcclitest/lib/python3.9/site-packages/prismacloud/cli/cwpp/cmd_version.py", line 4, in <module>
    from prismacloud.cli.api import pc_api
  File "/Users/[someuser]/Projects/pcclitest/lib/python3.9/site-packages/prismacloud/cli/api.py", line 264, in <module>
    pc_api.configure(map_cli_config_to_api_config())
  File "/Users/[someuser]/Projects/pcclitest/lib/python3.9/site-packages/prismacloud/cli/api.py", line 33, in map_cli_config_to_api_config
    settings = get_cli_config()
  File "/Users/[someuser]/Projects/pcclitest/lib/python3.9/site-packages/prismacloud/cli/api.py", line 100, in get_cli_config
    community_supported()  # Check if support message has been shown and accepted
  File "/Users/[someuser]/Projects/pcclitest/lib/python3.9/site-packages/prismacloud/cli/api.py", line 78, in community_supported
    with open(community_support_accepted, "w") as _accepted:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/[someuser]/.prismacloud/.community_supported_accepted'

## Expected behavior

Should create .prismacloud hidden folder in my home folder with  a .community_supported_accepted file in it.
## Current behavior

It errors as above

## Possible solution

I created the hidden folder and the hidden file and pc version worked

## Steps to reproduce

1. on Mac OSX 12.6 running python 3.10.7 pip3 install prismacloud-cli
2. run pc version
3. see it fail

## Context

Cannot try/test prismacloud-cli

## Your Environment

- Version used: prismacloud-cli    0.4.45 ,  prismacloud-api    4.0.8
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): iterm 3.4.16 SHELL: zsh python 3.10.7
- Operating System and version (desktop or mobile): desktop OSX Monterey 10.6 (21G115)
- Link to your project:

**Comment by dukekautington3rd** [comment]
@timberbee this was fixed in the last merge.  You'll have to update your prisma-cli.

https://github.com/PaloAltoNetworks/prismacloud-cli/pull/80#issue-1389711238

**Comment by steven-deboer** [comment]
Just tested and I don't get this error.
